name: RC

on:
  push:
    tags:
      - v*.*.*
jobs:
  gh-auto-release-note:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.current.outputs.tag }}
      previous: ${{ steps.previous.outputs.previous}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: extract
        run: |
          echo "cur_version=${GITHUB_REF##*/v}" >> $GITHUB_OUTPUT
          echo "cur_tag=${{github.ref_name}}" >> $GITHUB_OUTPUT
          echo "prev_tag=$(git describe --abbrev=0 --match='v*' --tags HEAD~)" >> $GITHUB_OUTPUT
      - name: Create release note content
        id: rn_content
        run: >-
          echo "rn_content=$(gh api
          --method POST
          -H "Accept: application/vnd.github+json"
          /repos/${{ github.repository}}/releases/generate-notes
          -f tag_name='${{steps.extract.outputs.cur_tag}}'
          -f previous_tag_name='${{steps.extract.outputs.prev_tag}}')" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create release note 
        run: >-
          gh api
          --method POST
          -H "Accept: application/vnd.github+json"
          /repos/${{ github.repository}}/releases
          -f tag_name='${{steps.extract.outputs.cur_tag}}'
          -f name='${{fromJson(steps.rn_content.outputs.rn_content).name}}'
          -f body="${{fromJson(steps.rn_content.outputs.rn_content).body}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  notify_new_version:
    name: Notify new version
    runs-on: ubuntu-20.04
    needs:
      - deploy
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - uses: bevolta/sqs-action@v0.2.2
        with:
          sqs-url: https://sqs.eu-west-1.amazonaws.com/692159125262/bevolta-import-test
          message: >-
            '{
            "version": "${{steps.extract.outputs.cur_tag}}"
            }'
          message-attributes: >-
            '{
              "MessageTypeName": {
                "DataType": "String",
                "StringValue": "NewVoltaVersionCreated"
              }
            }
            '
