name: RC

on:
  push:
    tags:
      - v*.*.*
jobs:
  volta_version:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.current.outputs.tag }}
      previous: ${{ steps.previous.outputs.previous}}
    steps:
      - uses: actions/checkout@v3
      - id: current
        run: echo "tag=${GITHUB_REF##*/v}" >> $GITHUB_OUTPUT
      - id: previous
        run: |
          previous_tag=`git describe --abbrev=0 --match='v*' --tags HEAD~`
          echo "previous=${previous_tag}" >> $GITHUB_OUTPUT
